"""Shared geometry and algorithm package for the TriangleMesh project."""

from .geometry import EPSILON, Point
from .planar import DCEL, DCELFace, DCELHalfEdge, DCELVertex, build_polygon_dcel, locate_face
from .visualization import generate_svg_path, save_svg, save_png
from .rectangle_packing import RectanglePacker
from .sequences import DavenportSchinzel
from .circle_packing import CirclePacker
from .distance_map import DistanceMapSolver
from .polygon_smoothing import PolygonalMeanCurvatureFlow
from .shapes import (
    Circle,
    Cube,
    Cuboid,
    Hexahedron,
    LineSegment,
    Plane,
    Ray,
    Rectangle,
    Shape,
    Shape2D,
    Shape3D,
    Sphere,
    Square,
    Tetrahedron,
    Triangle,
)
from .proximity import LargestEmptyCircle
from .mesh import (
    DynamicDelaunay,
    HexMesh,
    Mesh,
    MeshColoring,
    MeshTopology,
    MeshVoxelizer,
    OBJFileHandler,
    QuadMesh,
    TetMesh,
    TriMeshRefiner,
    TriangleMesh,
    build_topology,
    constrained_delaunay_triangulation,
    delaunay_flip,
    get_circle_boundary,
    get_square_boundary,
    get_voronoi_cells,
    triangulate,
)

__all__ = [
    "Circle",
    "CirclePacker",
    "Cube",
    "Cuboid",
    "DCEL",
    "DCELFace",
    "DCELHalfEdge",
    "DCELVertex",
    "DavenportSchinzel",
    "DistanceMapSolver",
    "DynamicDelaunay",
    "EPSILON",
    "HexMesh",
    "Hexahedron",
    "LargestEmptyCircle",
    "LineSegment",
    "Mesh",
    "MeshColoring",
    "MeshTopology",
    "MeshVoxelizer",
    "OBJFileHandler",
    "Plane",
    "Point",
    "PolygonalMeanCurvatureFlow",
    "QuadMesh",
    "Ray",
    "Rectangle",
    "RectanglePacker",
    "Shape",
    "Shape2D",
    "Shape3D",
    "Sphere",
    "Square",
    "TetMesh",
    "Tetrahedron",
    "TriMeshRefiner",
    "Triangle",
    "TriangleMesh",
    "build_polygon_dcel",
    "build_topology",
    "constrained_delaunay_triangulation",
    "delaunay_flip",
    "generate_svg_path",
    "get_circle_boundary",
    "get_square_boundary",
    "get_voronoi_cells",
    "locate_face",
    "save_svg",
    "save_png",
    "triangulate",
]
